services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    phpDocumentor\Guides\Compiler\NodeTransformer:
      tags: ['phpdoc.guides.compiler.nodeTransformers']
    phpDocumentor\Guides\Compiler\CompilerPass:
      tags: ['phpdoc.guides.compiler.passes']

  phpdoc.guides:
    namespace: phpDocumentor\Guides\
    exclude:
      - '%vendor_dir%/phpdocumentor/guides/src/Event/*'
      - '%vendor_dir%/phpdocumentor/guides/src/Nodes/*'
      - '%vendor_dir%/phpdocumentor/guides/src/Handlers/*'
      - '%vendor_dir%/phpdocumentor/guides/src/Intersphinx/*'
      - '%vendor_dir%/phpdocumentor/guides/src/Meta/*Entry.php'
      - '%vendor_dir%/phpdocumentor/guides/src/Meta/InternalTarget.php'
      - '%vendor_dir%/phpdocumentor/guides/src/Meta/*Entry.php'
      - '%vendor_dir%/phpdocumentor/guides/src/*Context.php'
      - '%vendor_dir%/phpdocumentor/guides/src/NodeRenderers/*'
      - '%vendor_dir%/phpdocumentor/guides/src/References/*'
      - '%vendor_dir%/phpdocumentor/guides/src/Renderer/*.php'
      - '%vendor_dir%/phpdocumentor/guides/src/Span/CrossReferenceNode.php'
      - '%vendor_dir%/phpdocumentor/guides/src/Span/*Token.php'
      - '%vendor_dir%/phpdocumentor/guides/src/Twig/*'
    resource: '%vendor_dir%/phpdocumentor/guides/src'

  phpDocumentor\Guides\Handlers\ParseFileHandler: ~


  phpDocumentor\Guides\Compiler\NodeTransformers\NodeTransformerFactory: '@phpDocumentor\Guides\Compiler\NodeTransformers\CustomNodeTransformerFactory'

  phpDocumentor\Guides\Parser:
    arguments:
      $parserStrategies: !tagged_iterator phpdoc.guides.parser.markupLanguageParser

  phpDocumentor\Guides\Compiler\Compiler:
    arguments:
      $passes: !tagged_iterator phpdoc.guides.compiler.passes

  phpDocumentor\Guides\Compiler\NodeTransformers\CustomNodeTransformerFactory:
    arguments:
      $transformers: !tagged_iterator phpdoc.guides.compiler.nodeTransformers
