imports:
  - { resource: 'guides.yml' }
  - { resource: 'guides-restructured-text.yml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  phpDocumentor\Guides\Console\:
    resource: '../../src'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['phpdoc.guides.command']

  Monolog\Logger:
    arguments:
      $name: 'app'

  Psr\Log\LoggerInterface: '@Monolog\Logger'
  Psr\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'
  Symfony\Component\EventDispatcher\EventDispatcher: ~


  phpDocumentor\Guides\Console\Application:
    public: true
    arguments:
      - !tagged phpdoc.guides.command

