name: "Coding Standards"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "phpDocumentor/.github/.github/workflows/coding-standards.yml@main"
    with:
      php-version: "8.0"
