# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

jobs:
  code-coverage:
    name: "Code Coverage"
    uses: "phpDocumentor/.github/.github/workflows/code-coverage.yml@main"

  coding-standards:
    name: "Coding Standards"
    uses: "phpDocumentor/.github/.github/workflows/coding-standards.yml@main"

  dependency-analysis:
    name: "Coding Standards"
    uses: "phpDocumentor/.github/.github/workflows/dependency-analysis.yml@main"

  lint:
    name: "Lint"
    uses: "phpDocumentor/.github/.github/workflows/lint.yml@main"

  static-analysis:
    name: "Static analysis"
    uses: "phpDocumentor/.github/.github/workflows/static-analysis.yml@main"

  unit-tests:
    name: "Unit test"
    uses: "phpDocumentor/.github/.github/workflows/continues-integration.yml@main"

  funtional-tests:
    name: "Functional test"
    uses: "phpDocumentor/.github/.github/workflows/continues-integration.yml@main"
    needs: "unit-tests"
    with:
      test-suite: "functional"
