# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

jobs:
  code-coverage:
    name: "Code Coverage"
    uses: "phpDocumentor/.github/.github/workflows/code-coverage.yml@v0.3.0"

  coding-standards:
    name: "Coding Standards"
    uses: "phpDocumentor/.github/.github/workflows/coding-standards.yml@v0.3.0"

  lint-root:
    name: "Lint root"
    uses: "phpDocumentor/.github/.github/workflows/lint.yml@main"
    with:
      composer-options: "--no-check-publish --ansi"

  static-analysis:
    name: "Static analysis"
    uses: "phpDocumentor/.github/.github/workflows/static-analysis.yml@v0.3.0"

  architecture:
    name: "Check architeture"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.25.0"
        with:
          coverage: "none"
          php-version: "8.2"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist"

      - name: "Check package level"
        run: "vendor/bin/deptrac --config-file deptrac.packages.yaml --formatter=github-actions"

  unit-tests:
    name: "Unit test"
    uses: "phpDocumentor/.github/.github/workflows/continues-integration.yml@v0.3.0"
    with:
      php-versions: "['7.4', '8.0', '8.1', '8.2']"

  funtional-tests:
    name: "Functional test"
    uses: "phpDocumentor/.github/.github/workflows/continues-integration.yml@v0.3.0"
    needs: "unit-tests"
    with:
      php-versions: "['7.4', '8.0', '8.1', '8.2']"
      test-suite: "functional --verbose"

  integration-tests:
    name: "integration test"
    uses: "phpDocumentor/.github/.github/workflows/continues-integration.yml@v0.3.0"
    needs: "unit-tests"
    with:
      php-versions: "['7.4', '8.0', '8.1', '8.2']"
      test-suite: "integration --verbose"
